complex_conditions:
  type: mapping
  label: 'Condition'
  mapping:
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: complex_conditions.complex_conditions.plugin.[%parent.plugin]
    parent:
      type: string
      label: 'Parent condition'
    depth:
      type: integer
      label: 'Depth'
    weight:
      type: integer
      label: 'Weight'
    negate_condition:
      type: boolean
      label: 'Negate'

complex_conditions.complex_conditions.plugin.*:
  type: complex_conditions_configuration

complex_conditions_configuration:
  type: mapping

complex_conditions.complex_conditions.plugin.entity_bundle:
  type: complex_conditions_configuration
  mapping:
    bundles:
      type: sequence
      label: 'Bundles'
      orderby: value
      sequence:
        type: string
        label: 'Bundle'

field.widget.settings.complex_conditions:
  type: mapping
  label: 'Conditions widget settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Entity types'
      orderby: value
      sequence:
        type: string
