conditions_plugin_reference:
  type: mapping
  label: 'Condition'
  mapping:
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: conditions_plugin_reference.conditions_plugin_reference.plugin.[%parent.plugin]
    parent:
      type: string
      label: 'Parent condition'
    depth:
      type: integer
      label: 'Depth'
    weight:
      type: integer
      label: 'Weight'
    negate_condition:
      type: boolean
      label: 'Negate'

conditions_plugin_reference.conditions_plugin_reference.plugin.*:
  type: conditions_plugin_reference_configuration

conditions_plugin_reference_configuration:
  type: mapping

conditions_plugin_reference.conditions_plugin_reference.plugin.entity_bundle:
  type: conditions_plugin_reference_configuration
  mapping:
    bundles:
      type: sequence
      label: 'Bundles'
      orderby: value
      sequence:
        type: string
        label: 'Bundle'

field.widget.settings.conditions_plugin_reference:
  type: mapping
  label: 'Conditions widget settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Entity types'
      orderby: value
      sequence:
        type: string
